sonar.projectKey=Samuel255231_SMARTHR-API
sonar.organization=samuel255231
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=dummy.lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=https://sonarcloud.io
sonar.auto.analysis.enabled=false
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.js
